name: Build

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildArm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r21e-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./build_android.sh
          
      - uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-Arm
          path: android

  buildArm64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r21e-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./build_android.sh

      - uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-Aarch64
          path: android

  # This workflow contains a single job called "build"
  buildx86:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r21e-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./build_android.sh
          
      - uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-x86
          path: android

  # This workflow contains a single job called "build"
  buildx86_64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install zip -y
          sudo apt install wget -y
          sudo apt install gcc-multilib -y
          sudo wget -P /home/runner/work/ "https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip"
          sudo chmod -R 777 *
          cd /home/runner/work
          sudo unzip android-ndk-r21e-linux-x86_64.zip
          sudo chmod -R 777 *
          
      - name: Build
        run: |
          ./build_android.sh
          
      - uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-x86_64
          path: android
